version: "3.8"
services:
  wesnoth:
    image: wesnoth:latest
    container_name: wesnoth-instance
    command: wesnoth
    # command: firefox
    environment:
      - DISPLAY # X11 forwarding
      - NVIDIA_VISIBLE_DEVICES=all # for nvidia graphics
      - NVIDIA_DRIVER_CAPABILITIES=graphics # for nvidia graphics
    volumes:
      - /tmp/.X11-unix # X11 forwarding
      - ./__data/local_share:/root/.local/share/wesnoth # user data, such as saves. for now we are using the root user in the container o_O
      - ./__data/cache:/root/.cache/wesnoth # user cache, looks like game-related cache data
      - ./__data/config:/root/.config/wesnoth # user settings, game preferences
    network_mode: host  # X11 forwarding
    deploy: # for nvidia graphics
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, graphics] # [gpu, graphics]

    devices:
      - /dev/snd:/dev/snd # for alsa sound
      - /dev/nvidia0:/dev/nvidia0 # for nvidia graphics
      - /dev/nvidiactl:/dev/nvidiactl # for nvidia graphics
